export default function Privacy() {
  const email = typeof process !== "undefined"
    ? (process.env.SUPPORT_EMAIL || "support@yourdomain.com")
    : "support@yourdomain.com";

  return (
    <div style={{
      maxWidth: "780px", margin: "48px auto", padding: "0 24px 80px",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      color: "#1a1a1a", lineHeight: "1.7",
    }}>
      <h1 style={{ fontSize: "32px", fontWeight: "700", marginBottom: "8px" }}>Privacy Policy</h1>
      <p style={{ color: "#666", marginBottom: "32px", fontSize: "14px" }}>
        Effective date: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <Section title="1. What We Collect">
        <p>Our Loyalty Points app collects and processes the following data to operate the rewards program:</p>
        <ul>
          <li>Customer email addresses and display names (to identify loyalty accounts)</li>
          <li>Shopify order IDs and purchase amounts (to calculate and award points)</li>
          <li>Points balances and transaction history</li>
          <li>Physical receipts submitted for review (stored as images/PDFs)</li>
          <li>Referral codes generated by customers</li>
          <li>Birthdays optionally submitted for birthday bonus rewards</li>
        </ul>
        <p>We do <strong>not</strong> collect payment card numbers, passwords, or government IDs.</p>
      </Section>

      <Section title="2. How We Use Your Data">
        <ul>
          <li>Track and display loyalty points balances in the storefront widget</li>
          <li>Award points automatically when orders are paid</li>
          <li>Generate Shopify discount codes when points are redeemed</li>
          <li>Send birthday bonus points on a customer's birthday month</li>
          <li>Attribute referrals and award referral bonuses</li>
          <li>Review submitted physical receipts for manual point awards</li>
        </ul>
      </Section>

      <Section title="3. Data Sharing">
        <p>
          We do <strong>not</strong> sell, rent, or share customer personal data with third parties
          for marketing purposes. Data is only shared with:
        </p>
        <ul>
          <li><strong>Shopify</strong> — to create discount codes via the Shopify API</li>
          <li><strong>Anthropic</strong> — if the AI chat assistant is enabled, messages and
            anonymised context (points balance, tier) are sent to Anthropic's API to generate responses</li>
        </ul>
      </Section>

      <Section title="4. Data Retention">
        <p>
          Customer data is retained as long as the app is installed on a Shopify store.
          Upon uninstall, all customer data for that store is permanently deleted within 30 days
          in response to the <code>shop/redact</code> webhook.
        </p>
      </Section>

      <Section title="5. Your Rights (GDPR / CCPA)">
        <p>Customers have the right to:</p>
        <ul>
          <li><strong>Access</strong> — request a copy of all data we hold about you</li>
          <li><strong>Deletion</strong> — request permanent deletion of all your data</li>
          <li><strong>Portability</strong> — receive your data in a machine-readable format</li>
        </ul>
        <p>
          To exercise these rights, contact the store that has the app installed, or email us
          directly at <a href={`mailto:${email}`} style={{ color: "#008060" }}>{email}</a>.
          We will respond within 30 days.
        </p>
      </Section>

      <Section title="6. Security">
        <p>
          All data is transmitted over HTTPS. Session tokens and admin credentials use
          HMAC-SHA256 signed tokens. Database access is restricted to the application server.
        </p>
      </Section>

      <Section title="7. Contact">
        <p>
          For privacy questions or data requests, contact us at:{" "}
          <a href={`mailto:${email}`} style={{ color: "#008060" }}>{email}</a>
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "32px" }}>
      <h2 style={{ fontSize: "18px", fontWeight: "600", marginBottom: "12px", color: "#111" }}>{title}</h2>
      <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        {children}
      </div>
    </div>
  );
}
